services:
  cache1:
    image: ml/go-distributed-cache
    build: ./
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADDR=cache1:8080
      - PEERS=cache2,cache3
  cache2:
    image: ml/go-distributed-cache
    build: ./
    restart: unless-stopped
    environment:
      - ADDR=cache2:8080
      - PEERS=cache1,cache3
  cache3:
    image: ml/go-distributed-cache
    build: ./
    restart: unless-stopped
    environment:
      - ADDR=cache3:8080
      - PEERS=cache1,cache2
