[cache]
addr = "localhost:8080"
peers = ["localhost:8081"]
capacity = 100
ttl = 3600

[grpc]
max_recv_msg_size = 4194304
max_send_msg_size = 4194304
rpc_timeout = 5  

rate_limit = 10
rate_limit_burst = 100
